### ISSUE TITLE
implement docker client

### ISSUE THREAD

**Issue by despiegk** [incubaid/crystaltools#10]

**Comment by Hamdy** [comment]
Docker client now works
- containers
 - list
 - halt
 - delete
 - save2image
 - export
 - load
  
- images
  - list
  - delete
  - export
  
- copying local ssh key to remote docker works now [Test added for this but commented]

**Comment by Hamdy** [comment]
@despiegk implemented! except for https://github.com/crystaluniverse/vlang_tools/issues/14  please check my comment there
