### ISSUE TITLE
build websites not working 

### ISSUE THREAD

**Issue by hossnys** [incubaid/crystaltools#129]
- after doing ```publishtools install ``` i tried to build threefold.io site using ```  publishtools build -r www_threefold_io``` but got this error

![Screenshot from 2022-05-19 15-56-01](https://user-images.githubusercontent.com/26298009/169315363-fc810277-762e-4ce6-bae4-456bd917b20f.png)

- and when checked which changes in this repo found that : 
![Screenshot from 2022-05-19 16-17-46](https://user-images.githubusercontent.com/26298009/169315892-7603278e-c87c-4c18-97a6-c1b33e985731.png)

**Comment by sameh-farouk** [comment]
in gittools It tries to append the part /tree/{branch-name} to git URLs that already have this part so it fails to find the repo.
Things we try, set multibranch to false in the config.json, not works. We also tried to remove the branch part manually from all config files, but This works only for URLs that don’t have a subdirectory.

**Comment by despiegk** [comment]
see crystalloin project
