### ISSUE TITLE
docker shell not done yet

### ISSUE THREAD

**Issue by despiegk** [incubaid/crystaltools#14]
![image](https://user-images.githubusercontent.com/6021844/103398333-88ca1c80-4b3c-11eb-8288-68ee47c223a8.png)

**Comment by Hamdy** [comment]
@despiegk what shell do you mean? like an object where you can execute commands on a remote machine?
may be node object?
Also this is blocked on the memory issue in ssh executor (reported to vlang) team

**Comment by despiegk** [comment]
just a way how to interactive open

ssh -A root@ ... os people end up in shell
is easy

**Comment by Hamdy** [comment]
method itself is implemented, needs some extra little work to test when ssh executor is fixed
can be done using `os.execvp("ssh", ["localhost", "-p $port"])`

**Comment by despiegk** [comment]
only need to work for local docker
