### ISSUE TITLE
ping on ipaddr not done

### ISSUE THREAD

**Issue by despiegk** [incubaid/crystaltools#15]
![image](https://user-images.githubusercontent.com/6021844/103399389-2d4e5d80-4b41-11eb-930f-f573256a32ec.png)

**Comment by Hamdy** [comment]
@despiegk
- `ping()` done 
- `check()` not done, still waiting for vlang team comment on an easy way to do it. regex module is not that clear how to use
- refactored `ipaddress` module, now it's better and differentiate between ipv6, and ipv4
