### ISSUE TITLE
easy rest API on publishing tools

### ISSUE THREAD

**Issue by despiegk** [incubaid/crystaltools#18]
- get markdown content 
- download file
- do a full text search
- ...

whatever needed to let gridsome use content from publishing tools

**Comment by Hamdy** [comment]
gridsome is static web site generator, it comes with all it needs and builds everything in a `dist` dir, 
generates html json files, and image dirs. this dir is best put behind nginx or so, 

we can server these static files using publishing tools, but this is not the proper use case for this, it has nothing to do with publishing tools here. this will be just to create a web server to serve static files

it will never be as efficient as nginx and in the same time vlang web framework does not support chunked transfer for files at the moment

**Comment by despiegk** [comment]
it doesn't matter, its still the best way how to do this
