### ISSUE TITLE
urgent crash in test script

### ISSUE THREAD

**Issue by despiegk** [incubaid/crystaltools#21]
- branch autoload
- make sure ssh-agent is loaded with a ssh key
- ```v -cg run publisher_t.v```

in examples directory of repo

**Comment by Hamdy** [comment]
no crash in ubuntu

**Comment by despiegk** [comment]
also

v test publisher

**Comment by Hamdy** [comment]
![image](https://user-images.githubusercontent.com/526328/104252102-e41fd700-5479-11eb-8c1d-c291050bf670.png)
