### ISSUE TITLE
templates should work

### ISSUE THREAD

**Issue by despiegk** [incubaid/crystaltools#24]
work with vlang tool untill the templates work
so we can use that to generate the docker files

**Comment by medvednikov** [comment]
They should work already. There's a test for this in the V repo:

```
fn one() string {
        name := 'Peter'
        age := 25
        numbers := [1, 2, 3]
        return $tmpl('1.txt')
}
```

1.txt

```
name: @name

age: @age

numbers: @numbers

@for number in numbers
@number
@end
```

It works with both local paths (the template must be in the directory the binary was launched from) and absolute paths.

**Comment by despiegk** [comment]
make example and commit to vlang github repo
