### ISSUE TITLE
lets prepare publishing env

### ISSUE THREAD

**Issue by despiegk** [incubaid/crystaltools#40]
- make sure flatten work
- when flatten put small config file in each website/wiki which has domain info
- use nodejs webserver to support domains (load the config file with domain info)
- fix the dns on/off
- https support directly in nodejs (no proxy)
- letsencrypt support for nodjs
- add https://www.npmjs.com/package/dns2 
- check memory usage with letsencrypt support nodjs & https & dns

**Comment by Hamdy** [comment]
#### Branch master

Digital twin
- [X] Let's Encrypt
- [X] HTTP && HTTPs
- [X] DNS Server

V Publisher
- [X] Flatten works now `v run publishtools.v run` works
- [X] Dns on/off `publishtools dns on/off`
- [X] Use domains
- [X] Add config file inside each website when flattening with its suported domains
- [X] Digital Twin node server support for domains for sites, wikis and errors
- [x] Let's encrypt (Add configurations for all domains read by DigitalTwin automatically upon server start
- [x] Add domains read by digital Twin to the DNS server
- [x] Docker file for DigitalTwin publisher
- [x] Hardening
