### ISSUE TITLE
pdf broken

### ISSUE THREAD

**Issue by despiegk** [incubaid/crystaltools#44]
![image](https://user-images.githubusercontent.com/6021844/111059408-ee704880-849d-11eb-8c0e-59e5718d8d95.png)

this used to work, pdf's need to be downloadable in development mode as well as in modejs mode

**Comment by Hamdy** [comment]
@despiegk this didn't use to work before. 
please update your crystallib with latest in branch (kristof) and 
`publishtools develop` after that

**Comment by Hamdy** [comment]
Reading pdf works, but now definitely after updating crystallib to latest (kristof) branch
flatten is not woring  and I think also pdf files are nor processed correctly 
this needs further look
