### ISSUE TITLE
Add support for docsify Charty maps

### ISSUE THREAD

**Issue by Hamdy** [incubaid/crystaltools#48]
Docsify-Charty for different charts support : https://github.com/markbattistella/docsify-charty

- [X] Added in crystallib
- [X] Docs https://github.com/crystaluniverse/publishtools/blob/development/docs/charts.md
- [X] Test
![image](https://user-images.githubusercontent.com/526328/113509874-21b36e00-9558-11eb-836f-f644f189700a.png)

**Comment by Hamdy** [comment]
- [X] Added in crystallib
- [ ] Docs

**Comment by Hamdy** [comment]
@despiegk  please verify

**Comment by despiegk** [comment]
documentation to publishtools documentation

TEST also
