### ISSUE TITLE
use tmux as process manager

### ISSUE THREAD

**Issue by Hamdy** [incubaid/crystaltools#52]
Improve digitaltwin command 
If you are using on localhost, please add flag `-d` or `--development`

- [x]  publishtools digitaltwin start
- [x] publishtools digitaltwin stop
- [X] publishtools digitaltwin restart
- [X] publishtools digitaltwin reload   (reload config in node, no need to restart) will detect new sites, etc
- [X] publishtools digitaltwin update  (pull latest digitaltwin code)
- [X] publishtools digitaltwin install
- [X] publishtools digitaltwin status `pm2 status server` if run in production
- [X] publishtools digitaltwin logs
- [x] -d or --development to run locally without pm2 (use on local host for easy debugging)

**Comment by despiegk** [comment]
fix to use tmux

**Comment by Hamdy** [comment]
fixed to use tmux
