### ISSUE TITLE
how to implement having 2 types of executors

### ISSUE THREAD

**Issue by despiegk** [incubaid/crystaltools#6]
see manifestor

- there is SSH executor and a local one, in python I can just change the executor for different types. 

![image](https://user-images.githubusercontent.com/6021844/103164781-bc8d0580-480f-11eb-8dfe-f9176d7784ef.png)

what we want is that the executor can be local or ssh but the Node.methods need to work on both

I guess needs to be done by Generics, but struggling how to get it to work

**Comment by Hamdy** [comment]
Through interfaces you could execute functions (define in the interface) 
However you can not (yet) access the variables defined in each type
as a work around we can have a function called may be `info(){}` defined in the interface as well as both types implementing this interface in our case `ExecutorLocal` & `ExecutorSSH` and then for each type it can return all relevant info in a map
examples
```
pub fn (mut executor ExecutorLocal) info() map[string]string{
	return {
		"category" : "local"
	}
}
```

```
pub fn (mut executor ExecutorSSH) info() map[string]string{
	return {
		"category" : "ssh",
		"sshkey": executor.sshkey
	}
}
```

**Comment by despiegk** [comment]
guess good enough for now
