### ISSUE TITLE
implement node_executor

### ISSUE THREAD

**Issue by despiegk** [incubaid/crystaltools#9]
only implemented one method, need to do some tests
use the docker functionality to get an SSH machine

**Comment by Hamdy** [comment]
node executors work both remotely and locally now
- added some tests for local executor
- added some test for ssh executors
- docker client works now over ssh executors with a test for this as well

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/103397821-44d61800-4b3a-11eb-82b8-0e6db90d0df7.png)

not done yet

**Comment by Hamdy** [comment]
@despiegk upload/download works fine on ssh executors, they are implemented there
because only in them we have the remote machine details
not sure what to do here in a local executor, rsync needs more info like ip, port, etc which means this is an ssh executor use case no?
