### ISSUE TITLE
macro to link pdf

### ISSUE THREAD

**Issue by despiegk** [incubaid/crystaltools#91]
I don't know how to make link to pdf in website
the links should find the pdf & link well, right now something goes wrong

![image](https://user-images.githubusercontent.com/6021844/115567880-05376580-a2bc-11eb-995c-a7867c02afe1.png)

becomes

![image](https://user-images.githubusercontent.com/6021844/115567912-0e283700-a2bc-11eb-976d-ad93f5246bd4.png)

**Comment by Hamdy** [comment]
this was fixed!
