### ISSUE TITLE
automatic def replacement doesn't work on longest match?

### ISSUE THREAD

**Issue by xmonader** [incubaid/crystaltools#95]
![image](https://user-images.githubusercontent.com/64129/120198788-d0a3bb80-c222-11eb-909a-67282cb2d59d.png)

error happens on this page https://staging.threefold.io/info/threefold#/internet4__tfgrid_primitives?id=network-uses-nu

expect to be able to browse to `peer2peeragent` not `peer2peer`

**Comment by Hamdy** [comment]
fixed, match is done on per (word) level
plz note : p2pagent is not included in the definitions at this point, that is why it's not matched
this is the source code `- p2pagent : p2p agent terminates the traffic coming from the webgw.`

![image](https://user-images.githubusercontent.com/526328/120306190-e58b5800-c2d1-11eb-9e1e-ea6fbedcf430.png)

**Comment by despiegk** [comment]
the fix of hamdy was wrong, need to redo, let kristof see
